name: "Terraform backend"

on:
  workflow_dispatch:
  push:
    paths:
      - "terraform-backend/**"
      - "terraform/**"

permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless of the GitHub Actions runner's operating system
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Initialize the terraform-backend directory
      - name: Terraform Backend Init
        working-directory: terraform-backend
        run: terraform init

      # Generates an execution plan for the terraform-backend directory
      - name: Terraform Backend Plan
        working-directory: terraform-backend
        run: terraform plan -input=false

      # Apply changes to the terraform-backend directory
      - name: Terraform Backend Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: terraform-backend
        run: terraform apply -auto-approve -input=false

      # Initialize the terraform directory
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      # Generates an execution plan for the terraform directory
      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -input=false

      # Apply changes to the terraform directory
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: terraform
        run: terraform apply -auto-approve -input=false
